In [1]:
import dyngen_utils

In [2]:
dyngen_utils.install(lib_loc='~/software/R/library', verbose=False)

Installing package in: ~/software/R/library

R[write to console]: Loading required package: remotes

In [3]:
dyngen_utils.get_backbones(lib_loc='~/software/R/library')

array(['bifurcating', 'bifurcating_converging', 'bifurcating_cycle',
       'bifurcating_loop', 'binary_tree', 'branching',
       'consecutive_bifurcating', 'converging', 'cycle', 'cycle_simple',
       'disconnected', 'linear', 'linear_simple', 'trifurcating'],
      dtype='<U23')

In [4]:
backbone = 'bifurcating'
data_cell_info, data_expression = dyngen_utils.generate_dataset(backbone=backbone, lib_loc='~/software/R/library')

Run Parameters:
	Backbone:  bifurcating
	Number of Cells:  500
	Number of TFs:  100
	Number of Targets:  50
	Number of HKs:  25
Generating TF network
Sampling feature network from real network
Generating kinetics for 175 features
Generating formulae
Generating gold standard mod changes
Precompiling reactions for gold standard
Running gold simulations
  |                                                  | 0 % elapsed=00s    |========                                          | 14% elapsed=01s, remaining~03s |===============                                   | 29% elapsed=01s, remaining~03s |======================                            | 43% elapsed=01s, remaining~02s |=============================                     | 57% elapsed=02s, remaining~01s |====================================              | 71% elapsed=02s, remaining~01s |===========================================       | 86% elapsed=03s, remaining~00s |==================================================| 100% elapsed=04s, remaining~00s
Precompiling reactions for simulations
Running 32 simulations
Mapping simulations to gold standard
Performing dimred
Simulating experiment
Wrapping dataset

In [5]:
data_cell_info

,cell_id,step_ix,simulation_i,sim_time,num_molecules,mult,lib_size
1,cell1,2730,30,130.083333,5651868.0,0.854729,4491286.0
2,cell2,1068,12,250.000000,5798384.0,1.234719,5399109.0
3,cell3,2354,26,90.083333,5688929.0,0.780281,4770219.0
4,cell4,1831,20,440.083333,6955417.0,2.145687,11709970.0
5,cell5,2444,27,60.000000,5594714.0,0.515414,3905967.0
...,...,...,...,...,...,...,...
496,cell496,423,5,310.083333,5629836.0,2.197818,4252428.0
497,cell497,432,5,400.083333,5493297.0,2.538605,2860334.0
498,cell498,1464,16,490.083333,7991997.0,2.114150,14369547.0
499,cell499,1043,12,0.000000,5300501.0,0.474905,2002584.0
500,cell500,1084,12,410.083333,6899120.0,0.707678,11609076.0

In [6]:
data_expression

,Burn1_TF1,Burn1_TF2,Burn1_TF3,Burn1_TF4,Burn2_TF1,Burn2_TF2,Burn2_TF3,Burn2_TF4,Burn3_TF1,Burn3_TF2,...,HK16,HK17,HK18,HK19,HK20,HK21,HK22,HK23,HK24,HK25
cell1,6.044394,5.459432,6.087463,6.781360,5.357552,6.357552,5.727920,5.672425,5.247928,5.882643,...,5.491853,5.781360,0.0,5.087463,6.339850,5.754888,6.629357,5.754888,6.442943,1.000000
cell2,6.247928,5.781360,6.741467,7.033423,4.807355,6.599913,5.643856,6.523562,6.044394,6.108524,...,6.209453,6.066089,1.0,5.285402,6.247928,6.000000,6.523562,5.614710,6.303781,2.000000
cell3,6.523562,6.000000,6.285402,6.807355,5.129283,6.554589,5.882643,5.930737,5.781360,5.357552,...,5.044394,5.727920,0.0,5.000000,6.442943,6.285402,6.584963,5.584963,6.672425,0.000000
cell4,6.820179,6.643856,7.665336,8.005625,5.700440,7.409391,6.988685,6.820179,6.672425,6.643856,...,6.832890,6.727920,0.0,6.339850,7.118941,7.011227,7.366322,6.768184,7.348728,2.584963
cell5,6.554589,5.426265,6.491853,6.339850,4.643856,5.781360,5.643856,5.247928,5.832890,5.426265,...,4.700440,5.727920,0.0,4.584963,6.209453,5.754888,6.375039,5.584963,6.022368,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cell496,6.129283,5.584963,6.442943,6.584963,4.906891,6.392317,5.882643,5.392317,5.930737,5.781360,...,5.977280,5.882643,0.0,4.700440,6.209453,5.523562,6.266787,5.754888,6.459432,2.000000
cell497,5.857981,5.209453,5.857981,6.149747,3.459432,6.149747,5.426265,5.044394,5.523562,5.523562,...,4.700440,4.700440,0.0,4.807355,5.754888,5.392317,5.781360,4.906891,5.906891,0.000000
cell498,6.832890,6.584963,7.741467,7.936638,6.339850,7.679480,6.930737,7.076816,6.845490,7.055282,...,6.629357,6.629357,2.0,5.930737,7.118941,6.857981,7.129283,6.614710,7.629357,1.000000
cell499,4.857981,4.754888,5.129283,5.977280,4.392317,5.459432,4.584963,4.754888,4.906891,4.584963,...,3.807355,3.906891,0.0,3.584963,4.247928,4.584963,5.754888,4.247928,5.044394,0.000000
cell500,7.087463,6.247928,7.546894,7.714246,6.266787,7.622052,6.569856,6.930737,6.523562,6.584963,...,6.643856,6.629357,0.0,6.409391,6.629357,7.066089,7.622052,6.882643,7.199672,1.584963